# Generated by Django 6.1.1 on 2026-09-05 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=64, unique=True)),
                ('required_levels', models.JSONField(default=list, help_text='Ordered list of minimum Role.level per approval step.')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=64)),
                ('target_model', models.CharField(max_length=128)),
                ('target_record_id', models.CharField(max_length=64)),
                ('step_index', models.PositiveSmallIntegerField()),
                ('required_level', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_model', 'target_record_id', 'step_index'],
                'unique_together': {('process', 'target_model', 'target_record_id', 'step_index')},
            },
        ),
    ]
