# Generated by Django 6.1.1 on 2026-09-05 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('computed', 'Computed'), ('paid', 'Paid')], default='pending', max_length=16)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text="Whatever Person 2's payroll engine returns: pro-rated pay, leave encashment, deductions, etc.")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
