# Generated by Django 6.1.1 on 2026-09-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_employee_bank_account'),
        ('payroll', '0002_payrun_payslip_payslipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_day', models.DateField()),
                ('unpaid_leave_encashment_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('prorated_basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('computed', 'Computed'), ('paid', 'Paid')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.employee')),
                ('final_payslip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement', to='payroll.payslip')),
            ],
        ),
    ]
