# Generated by Django 6.1.1 on 2026-09-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_employee_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('requires_allocation', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('affects_payroll', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='approved', max_length=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.employee')),
                ('time_off_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='timeoff.timeofftype')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('duration_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('refused', 'Refused')], default='draft', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='timeoff.allocation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_requests', to='core.employee')),
                ('time_off_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='timeoff.timeofftype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
