# Generated by Django 6.1.1 on 2026-09-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('refused', 'Refused'), ('cancelled', 'Cancelled')], default='draft', max_length=16),
        ),
    ]
