# Generated by Django 6.1.1 on 2026-09-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0002_alter_timeoffrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofftype',
            name='default_allocated_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
