# Generated by Django 6.1.1 on 2026-09-06 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0003_timeofftype_default_allocated_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocated_days',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='timeofftype',
            name='default_allocated_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
