# Generated by Django 6.1.1 on 2026-09-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('allowance', 'Allowance'), ('gross', 'Gross'), ('deduction', 'Deduction'), ('net', 'Net')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('computation_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('formula', 'Formula')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage_of_code', models.CharField(blank=True, max_length=30, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('pay_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly')], default='monthly', max_length=20)),
                ('rules', models.ManyToManyField(blank=True, related_name='structures', to='payroll.salaryrule')),
            ],
        ),
    ]
