# Generated by Django 6.1.1 on 2026-09-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrun_payslip_payslipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
