# Generated by Django 6.1.1 on 2026-09-06 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payslip_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrule',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]{2,30}$', '2–30 uppercase letters, numbers, or underscores.')]),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
