# Generated by Django 6.1.1 on 2026-09-05 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, help_text="e.g. 'timeoff.TimeOffRequest'", max_length=128)),
                ('record_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('diff', models.JSONField(blank=True, default=dict, help_text='e.g. {"status": ["submitted", "approved"], "notes": ["", "ok"]}')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model', 'record_id'], name='audit_audit_model_397d93_idx')],
            },
        ),
    ]
