# Generated by Django 6.1.1 on 2026-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
