# Generated by Django 6.1.1 on 2026-09-06 01:54

import secrets

from django.db import migrations, models


def backfill_qr_tokens(apps, schema_editor):
    Employee = apps.get_model("core", "Employee")
    for employee in Employee.objects.filter(qr_token=""):
        employee.qr_token = secrets.token_urlsafe(24)
        employee.save(update_fields=["qr_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qr_token',
            field=models.CharField(blank=True, editable=False, max_length=64, default=""),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_qr_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='qr_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
