# Generated by Django 6.1.1 on 2026-09-06 03:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='working_hours_per_week',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('80'))]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d{9,18}$', '9–18 digits, no spaces or dashes.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]{3,20}$', 'Use 3–20 letters, numbers, or hyphens only (e.g. EMP021).')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z][A-Za-z .'-]*$", 'Letters only (spaces, hyphens, and apostrophes allowed).')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z][A-Za-z .'-]*$", 'Letters only (spaces, hyphens, and apostrophes allowed).')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', '7–15 digits, optionally starting with + and a country code.')]),
        ),
    ]
